version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3015:3015'
      - '9229:9229'
    command: npm run start:dev
    env_file:
      - ./config/local.env
    networks:
      - webnet
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    networks:
      - webnet

networks:
  webnet:
