version: '3.8'

services:
  #  app:
  #    build:
  #      context: .
  #      target: development
  #    volumes:
  #      - .:/usr/src/app
  #      - /usr/src/app/node_modules
  #    ports:
  #      - '${PORT}:${PORT}'
  #      - '9229:9229'
  #    command: npm run start:dev
  #    depends_on:
  #      - mysql

  mysql:
    image: mysql
    hostname: ${DB_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'

  mongo:
    image: mongo
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}'
    volumes:
      - /data/db
