name: ci
on:
  pull_request:
    branches: ['*']

checks:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [20.x]

jobs:
  steps:
    - name: Copy repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install PNpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Lint code
      run: pnpm run lint

    - name: Build
      run: pnpm run build

  run:
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - name: Start Docker Compose services
        run: docker-compose up

      - name: Run additional checks
        run: |
          # Add your additional checks or tasks here
