name: ci
on:
  pull_request:
    branches: ['*']

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Start App
        run: pnpm run start &

